import React from 'react';
import Head from 'next/head';
import styles from '../styles/Template.module.css';
import Footer from '../Footer';


interface TemplateProps {
    children?: any;
}

export default function Template(props: TemplateProps) {
    return (
        <div className={styles.container}>
            <Head>
                <title>Hernande Monteiro - seu blog tech quentinho e atual!</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={styles.main}>
                <div className={styles.BoxContent}>
                    {props.children}
                </div>
                <Footer />
            </main>
        </div>
    )
}