import React from 'react';
import Head from 'next/head';
import styles from './Template.module.css';
import Footer from '../Footer';
import Header from '../Header';


interface TemplateProps {
    children?: any;
    nav?: any;
}

export default function Template(props: TemplateProps) {
    return (
        <div className={styles.container}>
            <Head>
                <title>Hernande Monteiro - seu blog tech quentinho e atual!</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Header />
            <main className={styles.main}>
                <div className={styles.BoxContent}>
                    <div className={styles.Content}>
                        {props.nav}
                        <div className={styles.ArticleBox}>
                            {props.children}
                        </div>
                    </div>
                </div>
                <Footer />
            </main>
        </div>
    )
}